# Generated by Django 2.2.5 on 2019-09-06 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('reference_url', models.URLField(max_length=128, null=True)),
                ('number_of_test_cases', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_story', models.IntegerField(default=0)),
                ('has_passed', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField()),
                ('is_automated', models.BooleanField(default=False)),
                ('criteria', models.TextField(max_length=512)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kewayy_app.Story')),
            ],
        ),
    ]
