# Generated by Django 2.2.5 on 2019-09-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kewayy_app', '0002_remove_story_number_of_test_cases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='position_in_story',
        ),
    ]
