# Generated by Django 2.2.5 on 2019-09-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kewayy_app', '0003_remove_testcase_position_in_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
