# Generated by Django 2.2.5 on 2019-09-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kewayy_app', '0007_auto_20190919_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='has_passed',
        ),
        migrations.AddField(
            model_name='testcase',
            name='status',
            field=models.NullBooleanField(choices=[(None, 'Not tested'), (True, 'Passed'), (False, 'Failed')]),
        ),
    ]
